name: test

permissions: {}

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.23.x', '1.24.x' ]
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: go test -v ./...
